#WARNING: Changing anything in the script will result making the program look ugly :P

#This is a following programm that has example about you are going to learn

import time
import random
#This will import time to your programm so you can make your programm run at the correct second

money1 = "$5/$7" #This contains the amount of money you will pay 
money2 = "$9/$12"
money3 = "$15/$17"
money4 = "$18/$20"
money5 = "$20/$23"
money6 = "$40/$45"
money7 = "$50"

emailid = "Please type in your email so we can give you your payment instructions" #This contains the email instructions

print("===TERMS AND CONDITIONS===")
time.sleep(1)
print("MESSAGE ", random.randint(1, 404), ":")
time.sleep(1)
print("Copying the formula of how the bot works is illegal and will lead you to jail.")
print("Typing unknown and illegal stuff will lead you to be banned.")
print("Your IP Address and location will be tracked to give you the best results.")
print("You will get offers from our products")
print("There will be SERVER ERRORS and other glitches. But do not WORRY")
print("Copyright Limited")
print("Upolies.CO")
print("Type \"agree\" if you agree to the TERMS AND CONDITIONS:")
if input() == "agree":
    print('')
    print('')
    print('')
    
    time.sleep(1) 
    print(" __      __         .__")
    print("/  \    /  \  ____  |  |    ____    ____    _____    ____  ")
    print("\   \/\/   /_/ __ \ |  |  _/ ___\  /  _ \  /     \ _/ __ \ ")
    print(" \        / \  ___/ |  |__\  \___ (  <_> )|  Y Y  \ \  ___/ ")
    print("  \__/\  /   \___  >|____/ \___  > \____/ |__|_|  / \___  >")
    print("       \/        \/            \/               \/      \/ ")
    print('')
    print("To Upolies Drinks")

    time.sleep(1)
    print('Book a Drink Shop')
    print('')
    time.sleep(1)
    print("By talking to our bot")
    time.sleep(1)
    print("Connecting to server...")
    print('')
    time.sleep(5)
    print("Do you want to book a drink in Pleasanton Drinking Shops? (yes or no)")
    if input() == "yes":
        time.sleep(1)
        print("Loading")
        time.sleep(4)
        print("U.Drinks_Bot: Do you want to book a drink in Ben's wine shop? (yes or no)") #if you say no, program breaks. Will be updated
        if input() == "yes":
            print("U.Drinks_Bot: Okay...")
            time.sleep(1)
            print("U.Drinks_Bot: Checking if shops are open...")
            time.sleep(3)
            print("U.Drinks_Bot: Shop is open")
            time.sleep(1)
            print("U.Drinks_Bot: The price is ", money3)
            time.sleep(1)
            print(emailid)
            input()
            time.sleep(1)
            print("U.Drinks_Bot: We have sent payment instructions")
            print("SERVER: WARNING: Don't leave yet")
            time.sleep(1)
            print("SERVER: Verification Code: ", random.randint(1, 1000000))
            print("SERVER: When you open the link in your mail. You must enter the code")
            time.sleep(2)
            print('')
            print("                           (")
            print("*                           )   *")
            print("              )     *      (")
            print("    )        (                   (")
            print("  (          )     (             )")
            print("    )    *           )        )  (")
            print("   (                (        (      *")
            print("    )          H     )        )")
            print("              [ ]            (")
            print("       (  *   |-|       *     )    (")
            print(" *      )     |_|        .          )")
            print("       (      | |    .  ")
            print(" )           /   \     .    ' .        *")
            print("(           |_____|  '  .    .  ")
            print(" )          | ___ |  \~~~/  ' .   (")
            print("        *   | \ / |   \_/  \~~~/   )")
            print("            | _Y_ |    |    \_/   (")
            print("*    wine   |-----|  __|__   |      *")
            print("            `-----`        __|__")
            time.sleep(2)
            print("U.Drinks_Bot: HAVE A NICE DRINK")
        else:
            print("Loading...")
            time.sleep(3)
            print("U.Drinks_Bot: Do you want to book a drink in Buffalo Wings? (yes or no)")
            if input() == "yes":
                print("U.Drinks_Bot: Okay..")
                time.sleep(1)
                print("U.Drinks_Bot: Checking if shop is open...")
                time.sleep(2)
                print("____")
                print("____")
                print("U.Drinks_Bot: Shop is open")
                time.sleep(1)
                print("U.Drinks_Bot: The price is ", money5)
                time.sleep(1)
                print("U.Drinks_Bot: ",emailid)
                input()
                time.sleep(1)
                print("U.Drinks_Bot: We have sent payment instructions")
                print("SERVER: WARNING: Don't leave yet")
                time.sleep(1)
                print("SERVER: Verification Code: ", random.randint(10000, 1000000))
                print("SERVER: When you open the link in your mail. You must enter the code")
                time.sleep(2)
                print('')
                print("                           (")
                print("*                           )   *")
                print("              )     *      (")
                print("    )        (                   (")
                print("  (          )     (             )")
                print("    )    *           )        )  (")
                print("   (                (        (      *")
                print("    )          H     )        )")
                print("              [ ]            (")
                print("       (  *   |-|       *     )    (")
                print(" *      )     |_|        .          )")
                print("       (      | |    .  ")
                print(" )           /   \     .    ' .        *")
                print("(           |_____|  '  .    .  ")
                print(" )          | ___ |  \~~~/  ' .   (")
                print("        *   | \ / |   \_/  \~~~/   )")
                print("            | _Y_ |    |    \_/   (")
                print("*    wine   |-----|  __|__   |      *")
                print("            `-----`        __|__")
                time.sleep(2)
                print("U.Drinks_Bot: HAVE A NICE DRINK")
            else:
                print("Loading...")
                print("U.Drinks_Bot: Do you want to book a drink in Swissland? (yes/no)")
                if input() == "yes":
                    print("U.Drinks_Bot: Okay..")
                    time.sleep(1)
                    print("U.Drinks_Bot: Checking if shop is open...")
                    time.sleep(2)
                    print("____")
                    print("____")
                    print("U.Drinks_Bot: Shop is open")
                    time.sleep(1)
                    print("U.Drinks_Bot: The price is ", money7)
                    time.sleep(1)
                    print("U.Drinks_Bot: ",emailid)
                    input()
                    time.sleep(1)
                    print("U.Drinks_Bot: We have sent payment instructions")
                    print("SERVER: WARNING: Don't leave yet")
                    time.sleep(1)
                    print("SERVER: Verification Code: ", random.randint(10000, 1000000))
                    print("SERVER: When you open the link in your mail. You must enter the code")
                    time.sleep(2)
                    print('')
                    print("                           (")
                    print("*                           )   *")
                    print("              )     *      (")
                    print("    )        (                   (")
                    print("  (          )     (             )")
                    print("    )    *           )        )  (")
                    print("   (                (        (      *")
                    print("    )          H     )        )")
                    print("              [ ]            (")
                    print("       (  *   |-|       *     )    (")
                    print(" *      )     |_|        .          )")
                    print("       (      | |    .  ")
                    print(" )           /   \     .    ' .        *")
                    print("(           |_____|  '  .    .  ")
                    print(" )          | ___ |  \~~~/  ' .   (")
                    print("        *   | \ / |   \_/  \~~~/   )")
                    print("            | _Y_ |    |    \_/   (")
                    print("*    wine   |-----|  __|__   |      *")
                    print("            `-----`        __|__")
                    time.sleep(2)
                    print("U.Drinks_Bot: HAVE A NICE DRINK")
                else:
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print('')
                    print("====SERVER-ERROR====")
                    print('MESSAGE', random.randint(1, 404), ":")
                    print("Bot is unable to produce results. Sorry, We will fix that issue.")
                    print("Try Again in ",random.randint(2, 10), "days and", random.randint(10, 100), "minutes")
    else:
        print("U.Drinks_Bot: Do you want to book a drink in Dublin? (yes/no)")
        if input() == "yes":
            print("U.Drinks_Bot: Okay..")
            time.sleep(1)
            print("U.Drinks_Bot: Do you want to book in Tim Tommy's win shop? (yes/no)")
            if input() == "yes":
                time.sleep(0.2)
                print("U.Drinks_Bot: Okay..")
                time.sleep(1)
                print("U.Drinks_Bot: Checking if shop is open...")
                time.sleep(2)
                print("____")
                print("____")
                print("U.Drinks_Bot: Shop is open")
                time.sleep(1)
                print("U.Drinks_Bot: The price is ", money7)
                time.sleep(1)
                print("U.Drinks_Bot: ",emailid)
                input()
                time.sleep(1)
                print("U.Drinks_Bot: We have sent payment instructions")
                print("SERVER: WARNING: Don't leave yet")
                time.sleep(1)
                print("SERVER: Verification Code: ", random.randint(10000, 1000000))
                print("SERVER: When you open the link in your mail. You must enter the code")
                time.sleep(2)
                print('')
                print("                           (")
                print("*                           )   *")
                print("              )     *      (")
                print("    )        (                   (")
                print("  (          )     (             )")
                print("    )    *           )        )  (")
                print("   (                (        (      *")
                print("    )          H     )        )")
                print("              [ ]            (")
                print("       (  *   |-|       *     )    (")
                print(" *      )     |_|        .          )")
                print("       (      | |    .  ")
                print(" )           /   \     .    ' .        *")
                print("(           |_____|  '  .    .  ")
                print(" )          | ___ |  \~~~/  ' .   (")
                print("        *   | \ / |   \_/  \~~~/   )")
                print("            | _Y_ |    |    \_/   (")
                print("*    wine   |-----|  __|__   |      *")
                print("            `-----`        __|__")
                time.sleep(2)
                print("U.Drinks_Bot: HAVE A NICE DRINK")
            else:
                print("Finding more places...")
                time.sleep(3)
                print("U.Drinks_Bot: Do you want to book a drink in Radians Glance's shop? (yes/no) ")
                if input() == "yes":
                    time.sleep(0.2)
                    print("U.Drinks_Bot: Okay..")
                    time.sleep(1)
                    print("U.Drinks_Bot: Checking if shop is open...")
                    time.sleep(2)
                    print("____")
                    print("____")
                    print("U.Drinks_Bot: Shop is open")
                    time.sleep(1)
                    print("U.Drinks_Bot: The price is ", money3)
                    time.sleep(1)
                    print("U.Drinks_Bot: ",emailid)
                    input()
                    time.sleep(1)
                    print("U.Drinks_Bot: We have sent payment instructions")
                    print("SERVER: WARNING: Don't leave yet")
                    time.sleep(1)
                    print("SERVER: Verification Code: ", random.randint(40000, 4000000))
                    print("SERVER: When you open the link in your mail. You must enter the code")
                    time.sleep(2)
                    print('')
                    print("                           (")
                    print("*                           )   *")
                    print("              )     *      (")
                    print("    )        (                   (")
                    print("  (          )     (             )")
                    print("    )    *           )        )  (")
                    print("   (                (        (      *")
                    print("    )          H     )        )")
                    print("              [ ]            (")
                    print("       (  *   |-|       *     )    (")
                    print(" *      )     |_|        .          )")
                    print("       (      | |    .  ")
                    print(" )           /   \     .    ' .        *")
                    print("(           |_____|  '  .    .  ")
                    print(" )          | ___ |  \~~~/  ' .   (")
                    print("        *   | \ / |   \_/  \~~~/   )")
                    print("            | _Y_ |    |    \_/   (")
                    print("*    wine   |-----|  __|__   |      *")
                    print("            `-----`        __|__")
                    time.sleep(2)
                    print("U.Drinks_Bot: HAVE A NICE DRINK")              
                else:
                    print("Do you want to book a shop in Curry Cravigs's shop? (yes/no)")
                    if input() == "yes":
                        time.sleep(0.2)
                        print("U.Drinks_Bot: Okay..")
                        time.sleep(1)
                        print("U.Drinks_Bot: Checking if shop is open...")
                        time.sleep(2)
                        
                        print("U.Drinks_Bot: Shop is open")
                        time.sleep(1)
                        print("U.Drinks_Bot: The price is ", money3)
                        time.sleep(1)
                        print("U.Drinks_Bot: ",emailid)
                        input()
                        time.sleep(1)
                        print("U.Drinks_Bot: We have sent payment instructions")
                        print("SERVER: WARNING: Don't leave yet")
                        time.sleep(1)
                        print("SERVER: Verification Code: ", random.randint(40000, 4000000))
                        print("SERVER: When you open the link in your mail. You must enter the code")
                        time.sleep(2)
                        print('')
                        print("                           (")
                        print("*                           )   *")
                        print("              )     *      (")
                        print("    )        (                   (")
                        print("  (          )     (             )")
                        print("    )    *           )        )  (")
                        print("   (                (        (      *")
                        print("    )          H     )        )")
                        print("              [ ]            (")
                        print("       (  *   |-|       *     )    (")
                        print(" *      )     |_|        .          )")
                        print("       (      | |    .  ")
                        print(" )           /   \     .    ' .        *")
                        print("(           |_____|  '  .    .  ")
                        print(" )          | ___ |  \~~~/  ' .   (")
                        print("        *   | \ / |   \_/  \~~~/   )")
                        print("            | _Y_ |    |    \_/   (")
                        print("*    wine   |-----|  __|__   |      *")
                        print("            `-----`        __|__")
                        time.sleep(2)
                        print("U.Drinks_Bot: HAVE A NICE DRINK")
                    else:
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        print('')
                        
                        print("====SERVER-ERROR====")
                        print('MESSAGE', random.randint(1, 404), ":")
                        print("Bot is unable to produce results. Sorry, We will fix that issue.")
                        print("Try Again in ", random.randint(70, 555), " minutes")
            
        else:
            print("")
            
else:
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print('')
    print("MESSAGE ", random.randint(1, 404), ":")
    print('')
    print('You have been disconnected from server since you did not agree to the terms.')
    print('Try Again')
    
        
