import time #Standard basis of time
import random #You know what random means :p
import nester #custom-file
#Annie96 is typing

print("Annie96 is typing")
print('_ _ _ _ _ _ _ _ _')
time.sleep(1)
print("This is one of the most creepiest chat history.")
print("Be ready for the horror...")
time.sleep(1)
print("Type \"ready\" if you are prepared:")
if input() == "ready":
	print("Transfered to port:", random.randint(1, 100)) 
	print(random.randint(10, 30), "people are watching this chat") #This is just show off
	print("")
	time.sleep(2)
	print("Annie96: Davey, are you there. probably not, you are sleeping")
	time.sleep(3)
	print("McDavey: I am online Annie, what are you doing?")
	time.sleep(2)
	print("Annie96: I am just sitting on my bed. What are you doing?")
	time.sleep(2)
	print("McDavey: I am studying")
	time.sleep(2)
	print("Annie96: Is that what you called Discord?")
	time.sleep(2)
	print("McDavey: No...")
	time.sleep(2)
	print("Annie96: Okay, Okay...")
	time.sleep(2)
	print("Annie96: It is very windy here, and also very loud..")
	time.sleep(2)
	print("McDavey: No wind here.")
	time.sleep(2)
	print("Annie96: Aww.. Lucky you")
	time.sleep(1)
	print("Annie96: I need my beauty sleep")
	time.sleep(3)
	print("McDavey: Damn Right you do")
	time.sleep(2)
	print("Annie96: Are you talking about how I look?! *_*")
	time.sleep(2)
	print("McDavey: Jk lol :)")
	time.sleep(1)
	print("Annie96: OMG")
	time.sleep(1)
	print("=====END OF PART 1=====")
	time.sleep(1)
	print("Part 2 starting in 10 seconds")
	time.sleep(1)
	print(random.randint(1, 7), "people left the port.")
	time.sleep(9)
	print('')
	print('=====START OF PART 2=====')
	time.sleep(1)
	print('')
	print("McDavey: What?! What is going on?")
	time.sleep(2)
	print("Annie96: How are you texting when you are digging a hole in my garden?")
	time.sleep(2)
	print("McDavey: What?! No way")
	time.sleep(0.5)
	print("McDavey: Stop joking around and be serious!!")
	time.sleep(2)
	print("Annie96: I am not, please believe me. I am being SERIOUS")
	time.sleep(0.5)
	print("Annie96: Anyway, why are you smiling like that towards me.")
	time.sleep(2)
	print("McDavey: Annie. THAT IS NOT ME.")
	time.sleep(1)
	print("Annie96: Then why is he wearing your red football jersy?")
	time.sleep(3)
	print("McDavey: What do you mean? My Jersy is in my closet")
	time.sleep(1)
	print("Annie96: OMG, HE IS IN THE HOUSE!!!!")
	time.sleep(1)
	print("McDavey: What!!? HIDE, run!!!")
	time.sleep(2)
	print('Annie96: I am already hiding inside the closet')
	time.sleep(2)
	print("McDavey: Annie, I think your fooling around with me..")
	time.sleep(2)
	print("Annie96: I AM NOT FOOLING around with you!!")
	time.sleep(1)
	print("McDavey: Okay stay put. I cannot resist anything happening to you...")
	time.sleep(1)
	print("Annie96: I never knew you felt like that about me..")
	time.sleep(0.5)
	print("Annie96: He is saying something!!!")
	time.sleep(1)
	print("Annie96: His voice is unlike yours")
	time.sleep(1)
	print("Annie96: His voice is echoing in the halls")
	time.sleep(2)
	print("Annie96: Davey?")
	time.sleep(1)
	print("McDavey: What does he say?")
	time.sleep(2)
	print("Annie96: \"COME OUT ANNIE\"")
	print("=====END OF PART 2=====")
	time.sleep(1)
	print("Part 3 starting in 10 seconds")
	time.sleep(1)
	print(random.randint(0, 1), "people left the port.")
	time.sleep(9)
	print('')
	print('=====START OF PART 3=====')
	time.sleep(1)
	print('')
	print("McDavey: I am calling the cops")
	time.sleep(1)
	print("McDavey: Stay put okay")
	time.sleep(2)
	print("McDavey: Annie?")
	time.sleep(1)
	print("Annie96: Oh no...")
	time.sleep(1)
	print("McDavey: What?!")
	time.sleep(2)
	print("Annie96: I sneezed and he heard me")
	time.sleep(0.5)
	print("Annie96: He is now scratching the closet's side!!!")
	time.sleep(1)
	print("McDavey: The police are coming in 10 mins. STAY PUT")
	time.sleep(1)
	print("=============one minute later=======================")
	time.sleep(2)
	print("Annie96: I can't believe it.")
	time.sleep(1)
	print("Annie96: There is no more sound")
	time.sleep(1)
	print("Annie96: It looks like he stopped!!")
	time.sleep(2)
	print("McDavey: Really?!")
	time.sleep(1)
	print("McDavey: Don't come out the closet till the police come")
	time.sleep(1)
	print("McDavey: Stay Put!!")
	time.sleep(1)
	print("Annie96: ok")
	time.sleep(2)
	print("Annie96: Davey...")
	time.sleep(1)
	print("Annie96: Can I tell you something?")
	time.sleep(2)
	print("McDavey: Tell me")
	time.sleep(2)
	print("Annie96: I never knew you liked me...")
	time.sleep(1)
	print("McDavey: Well..")
	time.sleep(1)
	print("Annie96: Could you come over to my house. Would ya?")
	time.sleep(2)
	print("McDavey: Yes. I will")
	time.sleep(1)
	print("Annie96: Thanks. I will be glad to see you. :)")
	time.sleep(3)
	print("McDavey: Annie..")
	time.sleep(2)
	print("McDavey: How do i know that this is you?")
	time.sleep(3)
	print("===========Annie96 went offline============")
	time.sleep(2)
	print('')
	print("Do you think this was the creepiest?")
	input()
	time.sleep(1)
	print(" Yes || No")
	print("  1M || 4K") #This is just for show-off
	print("")

	print("")
	print("")
	print("")
	print("====Disconnected====")
	

else:
        print("You have been disconnected")
